language: android
script: cd ./android && ./gradlew build
android:
  components:
  - build-tools-24.0.1
  - android-24

deploy:
  - provider: releases
    api_key:
      $GITHUB_API_KEY
    file: app/build/outputs/apk/app-release.apk
    on:
      repo: CodeLanka/Archaeology-Data-Collector-app
      tags: true

